export const siteMetadata = {
  title: 'Arman Hossen',
  author: 'Arman Hossen',
  headerTitle: 'armanhossen',
  description: 'Software Developer at Dropslab',
  language: 'en-us',
  theme: 'dark', // system, dark or light
  siteUrl: 'https://armanruet.github.io/',
  siteRepo: 'https://github.com/dlarroder/armanhossen-blog',
  siteLogo: '/static/images/logo.png',
  image: '/static/images/avatar.webp',
  socialBanner: '/static/images/twitter-card.png',
  email: 'hi@armanhossen.com',
  github: 'https://github.com/armanruet',
  twitter: 'https://x.com/arman_5227',
  facebook: 'https://facebook.com/dlarroder',
  linkedin: 'https://www.linkedin.com/in/armanruet/',
  medium: 'https://medium.com/@armanruet',
  locale: 'en-US',
};
